on:
  push:
    branches:
      - main

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python

      - uses: actions/checkout@v3
        if: ${{ steps.release.outputs.release_created }}

      - name: Build and publish to pypi
        if: ${{ steps.release.outputs.release_created }}
        uses: JRubics/poetry-publish@v1.11
        with:
          pypi_token: ${{ secrets.PYPI_TOKEN }}
          ignore_dev_requirements: "yes"
